### PR TITLE
Focus search input when overlay opens

### LINKED ISSUE #84: Opening the search overlay does not autofocus the input
## Description

Opening the search overlay by clicking the search icon in the header does not autofocus the input. It would be great to focus the input so that the user can just begin typing their search query without first needing to click on the input.

## Steps to Reproduce

1. Click the search icon in the header
2. Notice the input is not focused

## Expected Behaviour

The input is auto focused after opening the search overlay

### PR DESCRIPTION
**Pull request by roadlittledawn**
Closes #84 

This fixes the issue described in issue linked above. When search overlay opens it focuses the search input so a user can start typing.

We had to put it in a `setTimeout()` in order to wait out whatever was happening with `<Overlay />` component rendering. The CSS transitions that run on open took ~500ms. 100ms seemed to do the trick for the timeout though ¯\_(ツ)_/¯

### CODE REVIEW

File: packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js [hunk 1]
```diff
@@ -143,6 +154,7 @@ const InputView = ({ getAutocomplete, getInputProps }) => {
 
 SwiftypeSearch.propTypes = {
   className: PropTypes.string,
+  isOpen: PropTypes.bool,
```
Comment (caylahamann) [inline packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js:157]: We can remove this now because we aren't using it!

**Review by caylahamann — CHANGES_REQUESTED** [review]

File: packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js (hunk 1 above)
Comment (roadlittledawn) [reply packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js]: derp! thanks for catching that!

**Review by jerelmiller — APPROVED** [review]

**Review by caylahamann — APPROVED** [review]

**Comment by jpvajda** [comment]
@roadlittledawn did you still want this merged into the theme?

**Comment by roadlittledawn** [comment]
@jpvajda  Oh didn’t realize this didn’t get merged. I’d say let’s merge unless anyone else thinks differently

**Comment by jpvajda** [comment]
@jerelmiller  / @zstix  what do you think? Is this ok to merge? It's a nice change. :)
